version: '3.4'

services:
  naive:
    image: zai7lou/naiveproxy-docker
    container_name: naiveproxy
    ports:
      - 80:80
      - 443:443
    tty: true
    volumes:
      - ./data:/data
    command: ["/bin/bash", "/data/entry.sh"]